### ISSUE TITLE
tt-rss 1.7.8: undefined function theme_image()

### ISSUE THREAD

**Issue by cweiske** [versvs/ttrss2scuttle#2]
With tt-rss 1.7.8, I get the following fatal error:

> PHP Fatal error:  Call to undefined function theme_image() in /path/to/ttrss2scuttle/semanticscuttle/init.php on line 77

**Comment by versvs** [comment]
Thanks cweiske, I have not tested the plugin with the latest release of tt-rss. I'll look for this error as soon as I have a few minutes :)

**Comment by greencrab** [comment]
Hi, I've fixed this problem because of a deprecated function.  There's another bug that is fixed.  I'll send a pull request.

**Comment by versvs** [comment]
Thanks greencrab for the commit, it is a shame i took a few weeks to come back :(

sorry guys, i'll try to be faster next time :)
